version: '3.8'

services:
    php:
        build: ./docker/frankenphp
        ports:
            - "80:80"
            - "443:443"
            - "443:443/udp"
        volumes:
            - ./etc/caddy:/etc/caddy
            - ./:/app/
            - caddy_data:/data
            - caddy_config:/config
        tty: true
volumes:
    caddy_data:
    caddy_config:
